### ISSUE TITLE
Router documentation

### ISSUE THREAD

**Issue by harikt** [distillphp/distill#4]
Hi Ralph, 

From your comment on [somos](https://github.com/somos/framework/issues/34#issuecomment-90749176) it first looked nice. But seems not covering all ?

In Aura.Router what it does is creates all the formats like 

| Route Name    | HTTP Method   | Route Path            | Purpose
| ------------- | ------------- | --------------------- | -------
| blog.browse   | GET           | /blog{format}         | Browse multiple resources
| blog.read     | GET           | /blog/{id}{format}    | Read a single resource
| blog.edit     | GET           | /blog/{id}/edit       | The form for editing a resource
| blog.add      | GET           | /blog/add             | The form for adding a resource
| blog.delete   | DELETE        | /blog/{id}            | Delete a single resource
| blog.create   | POST          | /blog                 | Create a new resource
| blog.update   | PATCH         | /blog/{id}            | Update part of an existing resource
| blog.replace  | PUT           | /blog/{id}            | Replace an entire existing resource

So if you noticed the route 

```php
$app['hello-rest'] = ['/blog', 'BlogRestController->execute{__HTTP_METHOD__}'];
```

We can use `POST` to create a blog post, but get applies to a different url and delete represents to another. But I understand it gives a flexibility.

Another question is : 

How do you handle the params to be filtered ?

```php
/hello/:name
```

Where name is alphabetic or digits like that ?

**Comment by ralphschindler** [comment]
While you can build non-REST-ish routes in distill, that was never the first priority.  I'm unsure what {format} is suppose to be, but for the rest of the use cases, those are fairly easy to encompass in a few possible rules:

```http
GET,POST,PUT,DELETE,PATCH /blog[/:id#\d|add#[/:action#edit#]] // for id based routes, or id=add, optional edit
```
or mulitple
```http
GET /blog[/:id[/:action#edit#]]
GET /blog/add
GET,POST,PUT,DELETE,PATCH /blog[/:id#\d#]
```

As for *filtering*, there is none.  However something is presented in the URI portion of the HTTP request is how it will be parsed/used when presented to the dispatchable.  On the other hand, *validation* may be assigned (see the examples with the # symbols) and that will basically be context specific parameter matching, for those use cases.

I added some use cases to demonstrate possible rules:
https://github.com/distillphp/distill/blob/master/tests/Router/HttpRouteTest.php#L28-L157

**Comment by harikt** [comment]
> I'm unsure what {format} is suppose to be

Leave the format. Format will not add REST ful. It is basically `.json`, `.xml` etc helps in testing things.

Thank you for the test cases.
