### ISSUE TITLE
psr7 ?

### ISSUE THREAD

**Issue by harikt** [distillphp/distill#7]
Hi
Are you considering psr7 into core.

**Comment by ralphschindler** [comment]
I don't believe so.  Including support for psr-7 would be antithetical to the primary purpose of this application architecture, which is to allow developers to rely on the API's of PHP as much as possible when writing applications.

**Comment by ralphschindler** [comment]
That said, it still could go into an add-on/commons module. Still thinking on that though.

**Comment by harikt** [comment]
Hi @ralphschindler ,

Sorry to disturb you again.

Just wondering whether the new distill-framework will use any sort of PSR-7 , or what are the plans for next version.

I was re-reading your message regarding common module and wondering how do we make the `$request` / `$response` be passed with different events. Any thoughts ?

Thank you
